export default {
    GET_SUBSCRIPTION: 'GET_SUBSCRIPTION',
    GET_SUBSCRIPTION_REQUEST: 'GET_SUBSCRIPTION_REQUEST',
    GET_SUBSCRIPTION_SUCCESS: 'GET_SUBSCRIPTION_SUCCESS',
    GET_SUBSCRIPTION_FAILURE: 'GET_SUBSCRIPTION_FAILURE',

    ADD_SUBSCRIPTION: 'ADD_SUBSCRIPTION',
    ADD_SUBSCRIPTION_REQUEST: 'ADD_SUBSCRIPTION_REQUEST',
    ADD_SUBSCRIPTION_SUCCESS: 'ADD_SUBSCRIPTION_SUCCESS',
    ADD_SUBSCRIPTION_FAILURE: 'ADD_SUBSCRIPTION_FAILURE',

    CANCEL_SUBSCRIPTION: 'CANCEL_SUBSCRIPTION',
    CANCEL_SUBSCRIPTION_REQUEST: 'CANCEL_SUBSCRIPTION_REQUEST',
    CANCEL_SUBSCRIPTION_SUCCESS: 'CANCEL_SUBSCRIPTION_SUCCESS',
    CANCEL_SUBSCRIPTION_FAILURE: 'CANCEL_SUBSCRIPTION_FAILURE',
};
  