export default {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGIN_WITH_SOCIAL: 'LOGIN_WITH_SOCIAL',
  LOGIN_WITH_SOCIAL_REQUEST: 'LOGIN_WITH_SOCIAL_REQUEST',
  LOGIN_WITH_SOCIAL_SUCCESS: 'LOGIN_WITH_SOCIAL_SUCCESS',
  LOGIN_WITH_SOCIAL_FAILURE: 'LOGIN_WITH_SOCIAL_FAILURE',

  GET_INSTAGRAM_USER_PROFILE: 'GET_INSTAGRAM_USER_PROFILE',
  GET_INSTAGRAM_USER_PROFILE_REQUEST: 'GET_INSTAGRAM_USER_PROFILE_REQUEST',
  GET_INSTAGRAM_USER_PROFILE_SUCCESS: 'GET_INSTAGRAM_USER_PROFILE_SUCCESS',
  GET_INSTAGRAM_USER_PROFILE_FAILURE: 'GET_INSTAGRAM_USER_PROFILE_FAILURE',

  RESTORE_USER: 'RESTORE_USER',
  RESTORE_USER_REQUEST: 'RESTORE_USER_REQUEST',
  RESTORE_USER_SUCCESS: 'RESTORE_USER_SUCCESS',
  RESTORE_USER_FAILURE: 'RESTORE_USER_FAILURE',

  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',


  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

  VERIFY_CODE_PASSWORD: 'VERIFY_CODE_PASSWORD',
  VERIFY_CODE_PASSWORD_REQUEST: 'VERIFY_CODE_PASSWORD_REQUEST',
  VERIFY_CODE_PASSWORD_SUCCESS: 'VERIFY_CODE_PASSWORD_SUCCESS',
  VERIFY_CODE_PASSWORD_FAILURE: 'VERIFY_CODE_PASSWORD_FAILURE',

  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  CHANGE_AVATAR: 'CHANGE_AVATAR',
  CHANGE_AVATAR_REQUEST: 'CHANGE_AVATAR_REQUEST',
  CHANGE_AVATAR_SUCCESS: 'CHANGE_AVATAR_SUCCESS',
  CHANGE_AVATAR_FAILURE: 'CHANGE_AVATAR_FAILURE',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  CHANGE_EMAIL: 'CHANGE_EMAIL',
  CHANGE_EMAIL_REQUEST: 'CHANGE_EMAIL_REQUEST',
  CHANGE_EMAIL_SUCCESS: 'CHANGE_EMAIL_SUCCESS',
  CHANGE_EMAIL_FAILURE: 'CHANGE_EMAIL_FAILURE',

  CHANGE_PHONE: 'CHANGE_PHONE',
  CHANGE_PHONE_REQUEST: 'CHANGE_PHONE_REQUEST',
  CHANGE_PHONE_SUCCESS: 'CHANGE_PHONE_SUCCESS',
  CHANGE_PHONE_FAILURE: 'CHANGE_PHONE_FAILURE',

  CHANGE_ADDRESS: 'CHANGE_ADDRESS',
  CHANGE_ADDRESS_REQUEST: 'CHANGE_ADDRESS_REQUEST',
  CHANGE_ADDRESS_SUCCESS: 'CHANGE_ADDRESS_SUCCESS',
  CHANGE_ADDRESS_FAILURE: 'CHANGE_ADDRESS_FAILURE',

  GET_USER: 'GET_USER',
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',

  GET_CURRENT_USER: 'GET_CURRENT_USER',
  GET_CURRENT_USER_REQUEST: 'GET_CURRENT_USER_REQUEST',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',

  CHECK_EMAIL: 'CHECK_EMAIL',
  CHECK_EMAIL_REQUEST: 'CHECK_EMAIL_REQUEST',
  CHECK_EMAIL_SUCCESS: 'CHECK_EMAIL_SUCCESS',
  CHECK_EMAIL_FAILURE: 'CHECK_EMAIL_FAILURE',

  SET_CURRENT_USER: 'SET_CURRENT_USER',
  RESET_USER: 'RESET_USER',
};
